### PR TITLE
Send me $5

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by voldyman** [comment]
damn, i got late :(

**Comment by shazow** [comment]
Arg, so Github didn't notify me of this. THANKS GITHUB!

How would you like your payment? :D Want some bitcoins?

**Comment by dmitshur** [comment]
> Arg, so Github didn't notify me of this. THANKS GITHUB!

Were you [watching](https://github.com/shazow/sometalk-test/watchers) this repo? I see you are now, but were you before?

Do you have notifications turned on? Either web or email notifications?

image

Do you check them?

image

**Comment by shazow** [comment]
I was not watching it before, because I have 'Automatic watching' disabled. I do consulting work for other companies, so I often join organizations with tons of repos and I don't want notifications for all of them.

I guess disabling that also disabling watching of repos that I create, which makes far less sense.

**Comment by shazow** [comment]
Claimed in #4

**Pull request closed without merging**
