### PR TITLE
Delete main.py

### PR DESCRIPTION
**Pull request by NARKOZ**
`rm main.py`

### CODE REVIEW

**Comment by dmitshur** [comment]
See #1.

Not sure why it hasn't been merged.

**Comment by shazow** [comment]
I edited it to say it was claimed, but thought it'd be fun to keep the original for posterity. :)

**Comment by NARKOZ** [comment]
@shazow well, that's not fair. You changed terms _after_ I filed this pull request.

**Comment by shazow** [comment]
@NARKOZ You're right, I was intending on removing the code as soon as the first PR arrived but then changed my mind and thought it'd make more sense to keep it, so I changed the terms. The intention was to let the first person claim it, but I didn't write it in legalese. 

If @avrtno doesn't want the $5, then you can have it. :)

**Comment by NARKOZ** [comment]
@shazow she didn't claim it.

**Comment by shazow** [comment]
@NARKOZ Got a bitcoin address or somesuch?

**Comment by NARKOZ** [comment]
Bitcoin: 1PhFEfvimUmGJcK3okLoxbjpji1qHfZcbz
Amazon gift card: narkoz.2008 [at] gmail.com

**Comment by shazow** [comment]
@NARKOZ Sent 0.0184 BTC in txn [c56d21d25986a57035bea8fe2a1dd7bbf8c61219fbafc25db0eaafe3dbe7fc6c](https://blockchain.info/tx/c56d21d25986a57035bea8fe2a1dd7bbf8c61219fbafc25db0eaafe3dbe7fc6c), enjoy!

**Comment by NARKOZ** [comment]
@shazow wow, I thought it was a joke! Thank you very much!

That's just unbelievable. :+1:

**Comment by shazow** [comment]
@NARKOZ Jokes are funnier when they're real. :)

**Comment by NARKOZ** [comment]
@shazow thank you!

**Comment by shazow** [comment]
Welcome! :custard:

**Pull request closed without merging**
